### ISSUE TITLE
Reduce linter code-mangling

### ISSUE THREAD

**Issue by aparod** [RusticiSoftware/eslint-config-rusticisoftware#1]
It's valuable for teams to adopt the same code-style standards across the company, but the linter seems to have trouble with consistency and producing readable code even within a single file.  Could the linter's powers be reduced to only check for things like tab-vs-spaces or how to indent/line-break nested html tags, rather than reformatting the entire file?

Here's an example of code-mangling from the linter from [a recent PR](https://github.com/RusticiSoftware/ContentController/pull/6098#pullrequestreview-2139896849).  (I was so distracted by trying to make sense of the odd formatting that I didn't even notice until just now that one tooltip is nested within a `span` while the other is not.)

```html
<label style="width: fit-content">
    <input type="checkbox" id="update-scorm-export" />
    <span class="tooltip-hover"
        >Enable SCORM 2004 4th Edition Export
        <v-tooltip
            location="end top"
            origin="auto"
            activator="parent"
        >
            Enables or disabled SCORM 2004 4th Edition
            course sharing.
        </v-tooltip>
    </span>
</label>

<label style="width: fit-content">
    <input type="checkbox" id="update-rxd-enabled" />
    <span class="tooltip-hover"
        >Enable import of legacy RXD content</span
    >
    <v-tooltip
        location="end top"
        origin="auto"
        activator="parent"
    >
        Allows users to choose RXD v1.8 (legacy) instead of
        RXD v3.x (recommended) when importing RXD
        content.</v-tooltip
    >
</label>
```

**Comment by aparod** [comment]
@brianjmiller Wondered if you had any thoughts around this.  It's happening with pretty much every UI-related PR for the CC team.

Maybe there's some rationale for the way the linter is formatting things but none of us understand it, and it makes it harder for us to read/review the code.

**Comment by nwsop** [comment]
I've looked into it a bit now, and it's more to do with `@vue/eslint-config-prettier`, the Rustici linter has nothing to do with it. I don't think the styling issues in the template are really a problem. If you want to, set up a ticket in the CC repo. I'd close this ticket.

**Comment by brianjmiller** [comment]
+1, it seems odd that the prettier is doing that, but what it is producing is definitely not being dictated by the style rules as Nate indicated. I'll entertain changes to the styling rules, *but* the argument has to be very sound as pretty much all of the rules selected were done intentionally for one or the other and changing them at this point would potentially impact other products unless we just loosened them, but again the argument for loosening the style rules would need to be very well formed to convince me I suspect :-).

**Comment by aparod** [comment]
Sounds like it is just confusion on our end as to which tool is doing what.  If the Rustici linter isn't the cause of the weirdness then there's nothing to see here.  😄 

Sorry for the distraction!
